'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.239
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Finance_Management_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1331114349_backup_restore() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1331114349_backup-restore", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3d_spheres_1280_960_4624() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3d-spheres-1280-960-4624", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3d_spheres_1280_960_46241() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3d-spheres-1280-960-46241", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property creative_colorful_eye_creative_colorful_eye_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creative-colorful-eye-creative-colorful-eye-1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property creative_colorful_eye_creative_colorful_eye_1920x10801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creative-colorful-eye-creative-colorful-eye-1920x10801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property final1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("final1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property final2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("final2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fire_gIrl_fire_girl_2560x1600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire-gIrl-fire-girl-2560x1600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Graphic_Design_Light_graphic_design_light_1680x1050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Graphic-Design-Light-graphic-design-light-1680x1050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Graphic_Design_Light_graphic_design_light_1680x10501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Graphic-Design-Light-graphic-design-light-1680x10501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icontexto_webdev_reload_048x048() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icontexto-webdev-reload-048x048", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Mac_Art_by_mj_coffeeholick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mac_Art_by_mj-coffeeholick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property of_me_and_you_of_me_and_you_blue_abstract_1920x1080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("of-me-and-you-of-me-and-you-blue-abstract-1920x1080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property of_me_and_you_of_me_and_you_blue_abstract_1920x10801() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("of-me-and-you-of-me-and-you-blue-abstract-1920x10801", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property picture_935a40dba2_1680x1050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("picture-935a40dba2-1680x1050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stats_wallpaper_1024x768() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stats-wallpaper_1024x768", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Vista_Help_icon_by_Thoosje() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Vista_Help_icon_by_Thoosje", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property w3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("w3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wall_30() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wall_30", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property whitemagic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("whitemagic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ws_Ultimate_Vista_1600x1200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ws_Ultimate_Vista_1600x1200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
